services:
  db:
    image: postgres:13
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    networks:
      - app_network

  web:
    build: .
    command: gunicorn --timeout 120 --limit-request-line 8190 --limit-request-field_size 8190 --worker-connections 1000 longtailedleopardsaasproduct.wsgi:application --bind 0.0.0.0:8000
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - .:/app
      - static_volume:/app/static
    networks:
      - app_network
    env_file:
      - .env
    depends_on:
      - db
    # logging:
    #   driver: awslogs
    #   options:
    #     awslogs-region: "us-east-1"
    #     awslogs-group: "django-app-logs"
    #     awslogs-create-group: "true"
    #     awslogs-stream: "web"
        
  nginx:
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/static
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    depends_on:
      - web
    networks:
      - app_network
    # logging:
    #   driver: awslogs
    #   options:
    #     awslogs-region: "us-east-1"
    #     awslogs-group: "django-app-logs"
    #     awslogs-create-group: "true"
    #     awslogs-stream: "nginx"

volumes:
  static_volume:
  postgres_data:
  redis_data:

networks:
  app_network:
    driver: bridge
