# Generated by Django 4.2.11 on 2025-07-14 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orguser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
