# Generated by Django 4.2.11 on 2025-07-16 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_orguser_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='orguser',
            name='org_role',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
