# Generated by Django 3.2.25 on 2025-07-31 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_orguser_org_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orguser',
            name='org_role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(3, 'creator'), (4, 'manager')], null=True),
        ),
    ]
