# Generated by Django 3.2.25 on 2025-08-05 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_alter_orguser_org_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagestatus',
            name='thumbnail_url',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='usercontent',
            name='meta_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usercontent',
            name='thumbnail_url',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
    ]
