# Generated by Django 5.2 on 2025-06-06 12:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AlembicVersion",
            fields=[
                (
                    "version_num",
                    models.CharField(max_length=32, primary_key=True, serialize=False),
                ),
            ],
            options={
                "db_table": "alembic_version",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ImageStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_name", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "image_status",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("upload_date", models.DateTimeField(blank=True, null=True)),
                ("image_url", models.CharField(blank=True, max_length=500, null=True)),
                ("meta_data", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "image_status",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ImageTaskLogs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task_id", models.CharField(max_length=50, unique=True)),
                ("status", models.CharField(max_length=20)),
                ("result", models.TextField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "image_task_logs",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="InvoiceDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("currency", models.CharField(max_length=10)),
            ],
            options={
                "db_table": "invoice_details",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Invoices",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("invoice_id", models.CharField(max_length=100, unique=True)),
                ("invoice_date", models.DateTimeField()),
                ("complete_date", models.DateTimeField(blank=True, null=True)),
                ("total_amount", models.FloatField()),
            ],
            options={
                "db_table": "invoices",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="PaymentLogs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("log_id", models.IntegerField(unique=True)),
                ("timestamp", models.DateTimeField()),
                (
                    "log_message",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "db_table": "payment_logs",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="PaymentMethods",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "method_id",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                ("method_name", models.CharField(max_length=50)),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "db_table": "payment_methods",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="PaymentRefund",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "refund_id",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                ("charge_id", models.CharField(blank=True, max_length=50, null=True)),
                ("refund_status", models.CharField(max_length=50)),
                (
                    "balance_transaction",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("inten_id", models.CharField(max_length=50)),
                (
                    "reference_status",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("refund_date", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "payment_refund",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Payments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                ("payment_id", models.CharField(max_length=100, unique=True)),
                ("payment_date", models.DateTimeField(blank=True, null=True)),
                ("payment_amount", models.FloatField()),
                (
                    "refund_status",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                (
                    "subscription_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("is_subscription", models.BooleanField(blank=True, null=True)),
            ],
            options={
                "db_table": "payments",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="PaymentStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status_name", models.CharField(max_length=50)),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "subscription_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
            options={
                "db_table": "payment_status",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Products",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price_id", models.CharField(max_length=100, unique=True)),
                ("product_id", models.CharField(max_length=100, unique=True)),
                ("product_name", models.CharField(max_length=100)),
                (
                    "description",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("product_price", models.FloatField()),
                ("duration", models.CharField(max_length=50)),
                ("update_date", models.DateTimeField()),
                ("price_type", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "billing_scheme",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("is_active", models.BooleanField(blank=True, null=True)),
            ],
            options={
                "db_table": "products",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="TaxRates",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tax_id", models.CharField(blank=True, max_length=100, null=True)),
                ("tax_name", models.CharField(max_length=50)),
                ("tax_rate", models.FloatField()),
                (
                    "subscription_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
            options={
                "db_table": "tax_rates",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Usercontent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_url", models.CharField(blank=True, max_length=500, null=True)),
                ("video_url", models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                "db_table": "usercontent",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Users",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("authid", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=100, unique=True)),
                ("open_id", models.CharField(max_length=100)),
                ("stripe_customer_id", models.CharField(max_length=100, unique=True)),
                ("auth_type", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "image_profile",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("last_login", models.DateTimeField(blank=True, null=True)),
                ("password", models.CharField(blank=True, max_length=128)),
            ],
            options={
                "db_table": "users",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="MetaConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("meta_info", models.JSONField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "meta_configuration",
                "managed": True,
            },
        ),
    ]
