# Generated by Django 5.2 on 2025-06-06 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="metaconfiguration",
            options={"managed": False},
        ),
    ]
