"""modified payment related fields

Revision ID: 3fdd56d6c074
Revises: 5c92ca03c112
Create Date: 2025-01-30 15:34:33.655532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fdd56d6c074'
down_revision = '5c92ca03c112'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_refund',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('refund_id', sa.String(length=50), nullable=True),
    sa.Column('charge_id', sa.String(length=50), nullable=True),
    sa.Column('refund_status', sa.String(length=50), nullable=False),
    sa.Column('balance_transaction', sa.String(length=100), nullable=True),
    sa.Column('inten_id', sa.String(length=50), nullable=False),
    sa.Column('reference_status', sa.String(length=50), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('refund_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('refund_id')
    )
    with op.batch_alter_table('payment_methods', schema=None) as batch_op:
        batch_op.alter_column('method_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=50),
               existing_nullable=True)

    with op.batch_alter_table('payment_status', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subscription_id', sa.String(length=100), nullable=True))
        batch_op.drop_constraint('payment_status_status_id_key', type_='unique')
        batch_op.drop_column('sta_description')
        batch_op.drop_column('status_id')

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('refund_status', sa.String(length=15), nullable=True))
        batch_op.add_column(sa.Column('subscription_id', sa.String(length=100), nullable=True))

    with op.batch_alter_table('tax_rates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subscription_id', sa.String(length=100), nullable=True))
        batch_op.alter_column('tax_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=100),
               nullable=True)
        batch_op.drop_constraint('tax_rates_tax_id_key', type_='unique')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('auth_type', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('auth_type')

    with op.batch_alter_table('tax_rates', schema=None) as batch_op:
        batch_op.create_unique_constraint('tax_rates_tax_id_key', ['tax_id'])
        batch_op.alter_column('tax_id',
               existing_type=sa.String(length=100),
               type_=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('subscription_id')

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_column('subscription_id')
        batch_op.drop_column('refund_status')

    with op.batch_alter_table('payment_status', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('sta_description', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.create_unique_constraint('payment_status_status_id_key', ['status_id'])
        batch_op.drop_column('subscription_id')

    with op.batch_alter_table('payment_methods', schema=None) as batch_op:
        batch_op.alter_column('method_id',
               existing_type=sa.String(length=50),
               type_=sa.INTEGER(),
               existing_nullable=True)

    op.drop_table('payment_refund')
    # ### end Alembic commands ###
