"""added new fields to product table(isactive,billing_scheme,price_type)

Revision ID: 5c92ca03c112
Revises: 88719b4eb4c6
Create Date: 2025-01-24 18:49:52.549669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c92ca03c112'
down_revision = '88719b4eb4c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('billing_scheme', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('is_active')
        batch_op.drop_column('billing_scheme')
        batch_op.drop_column('price_type')

    # ### end Alembic commands ###
