"""added profile image field to user model

Revision ID: 8f7f878fb7f3
Revises: 7e9f7efb0a78
Create Date: 2025-04-03 15:30:35.087925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f7f878fb7f3'
down_revision = '7e9f7efb0a78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_profile', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('image_profile')

    # ### end Alembic commands ###
