"""modified image_status model

Revision ID: 9cf729d7d64b
Revises: fdb022d91ffd
Create Date: 2025-02-20 14:59:24.459608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9cf729d7d64b'
down_revision = 'fdb022d91ffd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image_status', schema=None) as batch_op:
        batch_op.add_column(sa.Column('meta_data', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image_status', schema=None) as batch_op:
        batch_op.drop_column('meta_data')

    # ### end Alembic commands ###
