"""added is_subscription to payments

Revision ID: eb1ebdb5e316
Revises: b0a27355d856
Create Date: 2025-02-03 16:06:16.098274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb1ebdb5e316'
down_revision = 'b0a27355d856'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_subscription', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_column('is_subscription')

    # ### end Alembic commands ###
