"""added a field to image_status

Revision ID: fdb022d91ffd
Revises: fbdf77214f59
Create Date: 2025-02-19 12:00:54.811357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdb022d91ffd'
down_revision = 'fbdf77214f59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image_status', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image_status', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
